'use client';
import { useState, useEffect, useRef } from 'react';
import AnimatedSection from '@/components/AnimatedSection';
/* OTONAMIPromo import kept for when promo section is restored */
// import OTONAMIPromo from '@/components/OTONAMIPromo';
import { DT as D } from '@/lib/design-tokens';

/* ── Light section tokens ── */
const L = {
  bg:       '#f0ede6',
  text:     '#2c1810',
  textSec:  '#6b4c3b',
  textMuted:'#9e7a6b',
  card:     '#ffffff',
  border:   'rgba(0,0,0,0.08)',
  shadow:   '0 2px 12px rgba(0,0,0,0.06)',
};

/* ─────────────────────────────────────────
   Bilingual copy
───────────────────────────────────────── */
const COPY = {
  en: {
    nav: {
      how: 'How it works', curators: 'For Curators', artists: 'For Artists',
      cta: 'Join as Curator →', lang: 'JA',
    },
    hero: {
      h1: ['Is your music actually reaching anyone?', 'OTONAMI delivers your tracks to people who truly listen.'],
      h1Gold: 1,
      sub: 'Send your tracks directly to international playlist curators, music bloggers, and radio DJs — and get professional feedback on every submission.',
    },
    how: {
      label: 'FOR ARTISTS & LABELS',
      title: 'Reach international media in 3 simple steps',
      steps: [
        { num: '1', t: 'Paste your track URL', d: 'Just paste a Spotify or YouTube link. AI analyzes your music automatically.' },
        { num: '2', t: 'AI matches you with the right curators', d: 'Based on genre, mood, and BPM, AI suggests the best international media for your music.' },
        { num: '3', t: 'AI writes & sends your English pitch', d: 'Professional English emails generated by AI. Send with one click and track opens, listens, and feedback in real time.' },
      ],
      cta: 'Try it free →',
    },
    footer: {
      tagline: 'Connecting Japanese Music to the World',
      links: [
        { label: 'For Curators', href: '/curator' },
        { label: 'For Artists',  href: '/artist' },
        { label: 'Contact',      href: 'mailto:info@otonami.io' },
      ],
      copy: '© 2026 TYCompany LLC',
      email: 'info@otonami.io',
    },
  },
  ja: {
    nav: {
      how: '使い方', curators: 'キュレーター（音楽メディア）の方', artists: 'アーティストの方',
      cta: 'キュレーター登録 →', lang: 'EN',
    },
    hero: {
      h1: ['配信した音楽、ちゃんと届いていますか？', 'あなたの曲を、本当に聴いてくれる人に届けます。'],
      h1Gold: 1,
      sub: '海外のプレイリスト運営者・音楽ブロガー・ラジオDJに、あなたの曲を直接届けて、プロのフィードバックをもらえるサービスです。',
    },
    how: {
      label: 'アーティスト・レーベルの方へ',
      title: '3ステップで、あなたの音楽を海外メディアに届けます',
      steps: [
        { num: '1', t: '曲のURLを入力', d: 'SpotifyやYouTubeのリンクを貼るだけ。AIが楽曲を自動分析します。' },
        { num: '2', t: 'あなたに合うメディアを自動マッチング', d: 'ジャンル・雰囲気・BPMをもとに、最適な海外メディアをAIが提案します。' },
        { num: '3', t: '英語の紹介文を自動作成＆送信', d: 'プロ品質の英語メールをAIが作成。ワンクリックで送信し、開封・試聴・返信をリアルタイムで確認。' },
      ],
      cta: '無料で試してみる →',
    },
    footer: {
      tagline: '日本の音楽を世界へ',
      links: [
        { label: 'キュレーター向け', href: '/curator' },
        { label: 'アーティスト向け', href: '/artist' },
        { label: 'お問い合わせ',     href: 'mailto:info@otonami.io' },
      ],
      copy: '© 2026 TYCompany LLC',
      email: 'info@otonami.io',
    },
  },
};

/* ─────────────────────────────────────────
   Shared helpers
───────────────────────────────────────── */
const wrap = { maxWidth: 1200, margin: '0 auto', padding: '0 24px' };

/* BlurText — reveals text segment by segment with blur-in effect */
function BlurText({ text, delay = 120, style: wrapStyle }) {
  const [visibleParts, setVisibleParts] = useState(0);
  const ref = useRef(null);
  const isJapanese = /[\u3000-\u9FFF]/.test(text);
  const parts = isJapanese
    ? text.split(/(?<=[。、！？\n])/g).filter(Boolean)
    : text.split(/\s+/);

  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    if (!('IntersectionObserver' in window)) { setVisibleParts(parts.length); return; }
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          let i = 0;
          const interval = setInterval(() => {
            i++;
            setVisibleParts(i);
            if (i >= parts.length) clearInterval(interval);
          }, delay);
          observer.unobserve(el);
        }
      },
      { threshold: 0.3 }
    );
    observer.observe(el);
    return () => observer.disconnect();
  }, [parts.length, delay]);

  return (
    <span ref={ref} style={wrapStyle}>
      {parts.map((part, i) => {
        const isVisible = i < visibleParts;
        return (
          <span
            key={i}
            style={{
              display: 'inline',
              opacity: isVisible ? 1 : 0,
              filter: isVisible ? 'blur(0px)' : 'blur(8px)',
              transition: `opacity 0.5s ease-out ${i * 0.05}s, filter 0.5s ease-out ${i * 0.05}s`,
            }}
          >
            {part}{!isJapanese && i < parts.length - 1 ? ' ' : ''}
          </span>
        );
      })}
    </span>
  );
}

/* ── FAQ Accordion ── */
function FAQItem({ question, answer, isOpen, onClick, theme = 'light' }) {
  return (
    <div style={{
      borderBottom: '1px solid #e5e2dc',
      paddingBottom: isOpen ? 16 : 0,
      marginBottom: 8,
    }}>
      <button
        className="faq-button"
        onClick={onClick}
        style={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          width: '100%',
          padding: '16px 0',
          background: 'none',
          border: 'none',
          cursor: 'pointer',
          textAlign: 'left',
          fontSize: 15,
          fontWeight: 600,
          color: '#1a1a1a',
          fontFamily: "'DM Sans', sans-serif",
        }}
      >
        {question}
        <span style={{
          fontSize: 18,
          color: '#c4956a',
          transform: isOpen ? 'rotate(45deg)' : 'rotate(0deg)',
          transition: 'transform 0.2s',
          flexShrink: 0,
        }}>+</span>
      </button>
      {isOpen && (
        <p style={{
          fontSize: 14,
          color: '#6b6560',
          lineHeight: 1.7,
          margin: '0 0 8px',
          paddingRight: 32,
          fontFamily: "'DM Sans', sans-serif",
        }}>
          {answer}
        </p>
      )}
    </div>
  );
}

/* ─────────────────────────────────────────
   Page
───────────────────────────────────────── */
export default function HomePage() {
  const [lang, setLang] = useState('ja');
  const [menuOpen, setMenuOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  const [openFaq, setOpenFaq] = useState(null);
  const menuRef = useRef(null);
  const canvasRef = useRef(null);

  /* ── Canvas waveform animation ── */
  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    let raf;

    const resize = () => {
      const dpr = window.devicePixelRatio || 1;
      const rect = canvas.parentElement.getBoundingClientRect();
      canvas.width = rect.width * dpr;
      canvas.height = rect.height * dpr;
      canvas.style.width = rect.width + 'px';
      canvas.style.height = rect.height + 'px';
      ctx.scale(dpr, dpr);
    };
    resize();
    window.addEventListener('resize', resize);

    let t = 0;
    const draw = () => {
      const W = canvas.width / (window.devicePixelRatio || 1);
      const H = canvas.height / (window.devicePixelRatio || 1);
      t++;
      ctx.clearRect(0, 0, W, H);

      /* Layer A: waveform bars */
      const barCount = 56;
      const barW = (W / barCount) * 0.5;
      const barGap = W / barCount;
      ctx.fillStyle = 'rgba(196, 149, 106, 0.10)';
      for (let i = 0; i < barCount; i++) {
        const x = i * barGap + (barGap - barW) / 2;
        const baseH = H * 0.12;
        const h = baseH + Math.sin(i * 0.35 + t * 0.015) * baseH * 0.7
                + Math.sin(i * 0.15 + t * 0.022) * baseH * 0.3;
        const y = H * 0.32 - h / 2;
        ctx.fillRect(x, y, barW, h);
      }

      /* Layer B: flowing waves */
      const layers = [
        { color: 'rgba(196,149,106,0.18)', amp: 28, freq: 0.008, speed: 0.015, yOff: 0.48 },
        { color: 'rgba(196,149,106,0.10)', amp: 18, freq: 0.012, speed: 0.02,  yOff: 0.53 },
        { color: 'rgba(232,93,58,0.08)',   amp: 22, freq: 0.006, speed: 0.01,  yOff: 0.58 },
        { color: 'rgba(196,149,106,0.05)', amp: 14, freq: 0.015, speed: 0.025, yOff: 0.63 },
      ];
      for (const l of layers) {
        ctx.beginPath();
        ctx.moveTo(0, H);
        for (let x = 0; x <= W; x += 2) {
          const y = H * l.yOff
            + Math.sin(x * l.freq + t * l.speed) * l.amp
            + Math.sin(x * l.freq * 2.3 + t * l.speed * 1.7) * l.amp * 0.4;
          ctx.lineTo(x, y);
        }
        ctx.lineTo(W, H);
        ctx.closePath();
        ctx.fillStyle = l.color;
        ctx.fill();
      }

      raf = requestAnimationFrame(draw);
    };
    raf = requestAnimationFrame(draw);

    return () => {
      cancelAnimationFrame(raf);
      window.removeEventListener('resize', resize);
    };
  }, []);

  useEffect(() => {
    try {
      const saved = localStorage.getItem('otonami_locale');
      if (saved === 'ja' || saved === 'en') { setLang(saved); return; }
      setLang(navigator.language?.startsWith('ja') ? 'ja' : 'en');
    } catch {}
  }, []);

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 20);
    window.addEventListener('scroll', onScroll, { passive: true });
    return () => window.removeEventListener('scroll', onScroll);
  }, []);

  useEffect(() => {
    if (!menuOpen) return;
    const h = (e) => { if (menuRef.current && !menuRef.current.contains(e.target)) setMenuOpen(false); };
    document.addEventListener('mousedown', h);
    return () => document.removeEventListener('mousedown', h);
  }, [menuOpen]);

  useEffect(() => {
    document.body.style.overflow = menuOpen ? 'hidden' : '';
    return () => { document.body.style.overflow = ''; };
  }, [menuOpen]);

  const switchLang = (l) => { setLang(l); try { localStorage.setItem('otonami_locale', l); } catch {} };
  const t = COPY[lang];

  /* FAQ data */
  const curatorFaqs = [
    {
      q: lang === 'en' ? 'How do I get paid?' : '報酬はどのように受け取れますか？',
      a: lang === 'en'
        ? 'You earn $1 or more for every pitch you respond to — whether you accept, decline, or leave feedback. Payouts are processed monthly via bank transfer.'
        : 'ピッチへの回答ごとに$1以上の報酬を受け取れます。採用・不採用・フィードバックのいずれでも支払われます。報酬は毎月銀行振込で処理されます。',
    },
    {
      q: lang === 'en' ? 'What kind of music will I receive?' : 'どのような音楽が届きますか？',
      a: lang === 'en'
        ? "Only pitches that match your genre preferences, mood settings, and audio profile. Our AI analyzes each track's audio features and matches it to your taste."
        : 'あなたのジャンル設定・ムード設定・音響プロフィールに合致するピッチのみ届きます。AIが各楽曲の音響特性を分析し、好みに合わせてマッチングします。',
    },
    {
      q: lang === 'en' ? 'Is it free to join as a curator?' : 'キュレーターの登録は無料ですか？',
      a: lang === 'en'
        ? 'Yes, completely free. You get paid for your time — artists pay the credits, not curators.'
        : 'はい、完全無料です。あなたの時間に対して報酬が支払われます。クレジットを支払うのはアーティスト側です。',
    },
  ];

  const artistFaqs = [
    {
      q: lang === 'en' ? 'What is a "curator"?' : '「キュレーター」って何ですか？',
      a: lang === 'en'
        ? 'Curators are music professionals who discover and share new music — playlist makers on Spotify/Apple Music, music bloggers, radio DJs, and online music magazines. When they feature your track, it reaches their audience of real music fans.'
        : 'キュレーターとは、新しい音楽を発見して紹介する音楽のプロフェッショナルです。Spotify/Apple Musicのプレイリスト運営者、音楽ブロガー、ラジオDJ、音楽ウェブマガジンなどが含まれます。彼らがあなたの曲を紹介すると、彼らのフォロワーである本物の音楽ファンに届きます。',
    },
    {
      q: lang === 'en' ? 'Do I need to write pitches in English?' : 'ピッチは英語で書く必要がありますか？',
      a: lang === 'en'
        ? 'No. Write in Japanese — our AI automatically generates a professional English pitch tailored to each curator.'
        : 'いいえ。日本語で入力するだけで、AIが各キュレーターに合わせたプロの英語ピッチを自動生成します。',
    },
    {
      q: lang === 'en' ? 'How much does it cost?' : '料金はいくらですか？',
      a: lang === 'en'
        ? 'Credits start from ¥160 each. Each pitch requires 1-5 credits depending on the curator. Registration is free.'
        : '1クレジット¥160〜。ピッチ送信にはキュレーターにより1〜5クレジットが必要です。登録は無料。',
    },
    {
      q: lang === 'en' ? 'When does OTONAMI launch?' : 'OTONAMIはいつローンチしますか？',
      a: lang === 'en'
        ? "We're launching in May 2026. Register now to set up your profile and tracks — you'll be ready to pitch on day one."
        : '2026年5月にローンチ予定です。今登録してプロフィールと楽曲を準備しておけば、初日からピッチできます。',
    },
  ];

  return (
    <div style={{ minHeight: '100vh', background: D.bg, fontFamily: D.fBody, color: D.text }}>

      <style>{`
        *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
        html { scroll-behavior: smooth; }
        body { background: ${D.bg}; overflow-x: hidden; -webkit-font-smoothing: antialiased; }
        ::selection { background: rgba(196,149,106,0.3); color: ${D.text}; }
        ::-webkit-scrollbar { width: 6px; }
        ::-webkit-scrollbar-track { background: transparent; }
        ::-webkit-scrollbar-thumb { background: rgba(255,255,255,0.12); border-radius: 3px; }

        @keyframes fadeInUp {
          from { opacity: 0; transform: translateY(18px); }
          to   { opacity: 1; transform: translateY(0); }
        }
        .hero-line     { display: block; }
        .hero-tag-anim { opacity: 0; animation: fadeInUp 0.6s ease 0.02s forwards; }
        .hero-sub-anim { opacity: 0; animation: fadeInUp 0.6s ease 0.52s forwards; }
        .hero-cta-anim { opacity: 0; animation: fadeInUp 0.6s ease 0.64s forwards; }

        .cta-coral {
          background: #e85d3a; color: #fff; border: none;
          padding: 14px 28px; border-radius: 9999px;
          font-size: 15px; font-weight: 600; cursor: pointer;
          transition: background 0.2s, transform 0.15s, box-shadow 0.15s;
          text-decoration: none; display: inline-block; font-family: inherit; white-space: nowrap;
        }
        .cta-coral:hover { background: #d04e2e; transform: translateY(-2px); box-shadow: 0 6px 20px rgba(232,93,58,0.35); }

        .cta-ghost {
          background: transparent; color: ${D.textSec};
          border: 1px solid rgba(255,255,255,0.18);
          padding: 14px 28px; border-radius: 9999px;
          font-size: 15px; font-weight: 500; cursor: pointer;
          transition: border-color 0.2s, color 0.2s, transform 0.15s;
          text-decoration: none; display: inline-block; font-family: inherit; white-space: nowrap;
        }
        .cta-ghost:hover { border-color: rgba(255,255,255,0.35); color: ${D.text}; transform: translateY(-2px); }

        .nav-link { color: ${D.textSec}; text-decoration: none; font-size: 13px; font-weight: 400; transition: color 0.2s, background 0.2s; white-space: nowrap; border-radius: 9999px; padding: 8px 16px; }
        .nav-link:hover { color: ${D.text}; background: rgba(255,255,255,0.1); }

        /* Light theme card */
        .how-card-light {
          background: #fff; border: 1px solid rgba(0,0,0,0.08); border-radius: 12px; padding: 32px 28px;
          box-shadow: 0 2px 12px rgba(0,0,0,0.06);
          transition: transform 0.2s, box-shadow 0.2s, border-color 0.2s;
          height: 100%;
        }
        .how-card-light:hover { transform: translateY(-4px); box-shadow: 0 8px 24px rgba(0,0,0,0.1); border-color: rgba(196,149,106,0.3); }

        /* Responsive */
        @media (max-width: 768px) {
          .nav-desktop-links { display: none !important; }
          .hamburger-btn { display: flex !important; }
          .hero-h1 { font-size: 34px !important; }
          .how-grid { grid-template-columns: 1fr !important; }
          .two-col { grid-template-columns: 1fr !important; }
          .cta-group { flex-direction: column !important; width: 100% !important; }
          .cta-group .cta-coral,
          .cta-group .cta-ghost { width: 100% !important; text-align: center !important; }
          .section-pad { padding: 72px 0 !important; }
          .footer-links { flex-direction: column !important; gap: 12px !important; }
          .lang-toggle { order: -1; }
        }
        @media (max-width: 480px) {
          .hero-h1 { font-size: 28px !important; }
        }
      `}</style>

      {/* ── Mobile menu ── */}
      {menuOpen && (
        <div ref={menuRef} style={{ position: 'fixed', inset: 0, zIndex: 300, background: '#181818', display: 'flex', flexDirection: 'column', padding: '0 24px' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', height: 64, borderBottom: `1px solid ${D.border}` }}>
            <span style={{ fontFamily: D.fHead, fontSize: 18, letterSpacing: '2px', color: D.text }}>OTONAMI</span>
            <button onClick={() => setMenuOpen(false)} style={{ background: 'none', border: 'none', color: D.textSec, fontSize: 28, cursor: 'pointer', lineHeight: 1, padding: 4 }}>✕</button>
          </div>
          <nav style={{ display: 'flex', flexDirection: 'column', gap: 4, paddingTop: 24 }}>
            <div style={{ display: 'flex', gap: 8, padding: '14px 0', borderBottom: `1px solid ${D.border}` }}>
              <button onClick={() => { switchLang('en'); setMenuOpen(false); }} style={{
                fontFamily: D.fBody, fontSize: 16, fontWeight: 600, padding: '10px 24px',
                borderRadius: 9999, border: 'none', cursor: 'pointer',
                background: lang === 'en' ? '#fff' : 'rgba(255,255,255,0.08)',
                color: lang === 'en' ? '#1a1a1a' : 'rgba(255,255,255,0.6)',
                transition: 'all 0.2s ease',
              }}>EN</button>
              <button onClick={() => { switchLang('ja'); setMenuOpen(false); }} style={{
                fontFamily: D.fBody, fontSize: 16, fontWeight: 600, padding: '10px 24px',
                borderRadius: 9999, border: 'none', cursor: 'pointer',
                background: lang === 'ja' ? '#fff' : 'rgba(255,255,255,0.08)',
                color: lang === 'ja' ? '#1a1a1a' : 'rgba(255,255,255,0.6)',
                transition: 'all 0.2s ease',
              }}>JP</button>
            </div>
            {[{ href: '#how-it-works', label: t.nav.how }, { href: '#for-curators', label: t.nav.curators }, { href: '#for-artists', label: t.nav.artists }].map(item => (
              <a key={item.href + item.label} href={item.href} onClick={() => setMenuOpen(false)}
                style={{ color: D.textSec, textDecoration: 'none', fontSize: 20, fontWeight: 400, padding: '14px 0', borderBottom: `1px solid ${D.border}`, transition: 'color 0.2s' }}
                onMouseEnter={e => e.target.style.color = D.text}
                onMouseLeave={e => e.target.style.color = D.textSec}
              >{item.label}</a>
            ))}
          </nav>
          <div style={{ marginTop: 32 }}>
            <a href="/curator" className="cta-coral" style={{ width: '100%', textAlign: 'center', display: 'block' }}>{t.nav.cta}</a>
          </div>
        </div>
      )}

      {/* ========== SECTION 1: HEADER (sticky nav) ========== */}
      <header className="liquid-glass" style={{
        position: 'fixed', top: 0, left: 0, right: 0, zIndex: 200,
        transition: 'background 0.3s',
      }}>
        <div style={{ ...wrap, display: 'flex', alignItems: 'center', justifyContent: 'space-between', height: 64 }}>
          <a href="/" style={{ textDecoration: 'none', fontFamily: D.fHead, fontSize: 20, letterSpacing: '2px', color: D.text, fontWeight: 500 }}>OTONAMI</a>
          <nav className="nav-desktop-links nav-links liquid-glass" style={{ display: 'flex', alignItems: 'center', gap: 4, borderRadius: 9999, padding: '4px 4px' }}>
            <a href="#for-curators" className="nav-link">{t.nav.curators}</a>
            <a href="#for-artists"  className="nav-link">{t.nav.artists}</a>
          </nav>
          <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
            <div className="lang-toggle" style={{ display: 'flex', background: 'rgba(255,255,255,0.08)', borderRadius: 9999, padding: 3, gap: 2 }}>
              <button onClick={() => switchLang('en')} style={{
                fontFamily: D.fBody, fontSize: 14, fontWeight: 600, padding: '8px 16px',
                borderRadius: 9999, border: 'none', cursor: 'pointer',
                background: lang === 'en' ? '#fff' : 'transparent',
                color: lang === 'en' ? '#1a1a1a' : 'rgba(255,255,255,0.6)',
                transition: 'all 0.2s ease',
              }}>EN</button>
              <button onClick={() => switchLang('ja')} style={{
                fontFamily: D.fBody, fontSize: 14, fontWeight: 600, padding: '8px 16px',
                borderRadius: 9999, border: 'none', cursor: 'pointer',
                background: lang === 'ja' ? '#fff' : 'transparent',
                color: lang === 'ja' ? '#1a1a1a' : 'rgba(255,255,255,0.6)',
                transition: 'all 0.2s ease',
              }}>JP</button>
            </div>
            <a href="/curator" className="cta-coral" style={{ padding: '8px 20px', fontSize: 13 }}>{t.nav.cta}</a>
            <button className="hamburger-btn" onClick={() => setMenuOpen(true)} style={{
              display: 'none', background: 'none', border: `1px solid ${D.border}`,
              borderRadius: 9999, width: 44, height: 44, fontSize: 18, cursor: 'pointer',
              color: D.textSec, alignItems: 'center', justifyContent: 'center',
            }}>☰</button>
          </div>
        </div>
      </header>

      {/* ========== SECTION 2: HERO ========== */}
      <section style={{
        position: 'relative', overflow: 'hidden',
        backgroundImage: `linear-gradient(rgba(26,26,26,0.72), rgba(26,26,26,0.96)), url('/images/hero-sxsw-crowd.jpg')`,
        backgroundSize: 'cover', backgroundPosition: 'center 30%', backgroundRepeat: 'no-repeat',
        paddingTop: 160, paddingBottom: 100,
      }}>
        <canvas ref={canvasRef} style={{ position: 'absolute', inset: 0, zIndex: 0, opacity: 0.5, pointerEvents: 'none' }} />
        <div style={{ ...wrap, textAlign: 'center', position: 'relative', zIndex: 1 }}>

          {/* Launch Badge */}
          <div className="hero-tag-anim launch-badge" style={{
            display: 'inline-flex',
            alignItems: 'center',
            gap: 10,
            padding: '8px 20px',
            borderRadius: 9999,
            background: 'rgba(196, 149, 106, 0.12)',
            border: '1px solid rgba(196, 149, 106, 0.25)',
            marginBottom: 24,
          }}>
            <span style={{
              width: 8,
              height: 8,
              borderRadius: '50%',
              background: '#c4956a',
              boxShadow: '0 0 8px rgba(196,149,106,0.6)',
              animation: 'pulse-dot 2s ease-in-out infinite',
              flexShrink: 0,
            }} />
            <span style={{
              fontSize: 13,
              fontWeight: 600,
              color: '#c4956a',
              letterSpacing: '0.5px',
            }}>
              {lang === 'en'
                ? 'Launching May 2026 — Early registration now open'
                : '2026年5月ローンチ — 先行登録受付中'}
            </span>
          </div>

          <h1 className="hero-h1 hero-heading" style={{ fontFamily: D.fHead, fontSize: 52, fontWeight: 500, lineHeight: 1.2, color: D.text, marginBottom: 28, letterSpacing: '-0.5px' }}>
            {t.hero.h1.map((line, i) => (
              <span key={i} className="hero-line" style={{ display: 'block', color: i === t.hero.h1Gold ? '#c4956a' : D.text }}>
                <BlurText text={line} delay={120} />
              </span>
            ))}
          </h1>

          <p className="hero-sub hero-sub-anim hero-desc" style={{
            fontSize: 17,
            color: 'rgba(255,255,255,0.75)',
            maxWidth: 540,
            margin: '0 auto 32px',
            lineHeight: 1.7,
          }}>
            {t.hero.sub}
          </p>

          {/* Dual CTAs */}
          <div className="hero-cta-anim hero-cta-group" style={{
            display: 'flex',
            gap: 16,
            flexWrap: 'wrap',
            justifyContent: 'center',
          }}>
            <a href="/curator" className="hero-cta-primary" style={{
              display: 'inline-flex',
              alignItems: 'center',
              gap: 8,
              padding: '14px 32px',
              borderRadius: 9999,
              background: '#c4956a',
              color: '#fff',
              fontWeight: 600,
              fontSize: 15,
              textDecoration: 'none',
              boxShadow: '0 4px 20px rgba(196,149,106,0.3)',
              transition: 'transform 0.2s, box-shadow 0.2s',
            }}>
              {lang === 'en' ? 'Register as Curator →' : 'キュレーター（音楽メディア）として登録 →'}
            </a>
            <a href="/artist" className="hero-cta-secondary" style={{
              display: 'inline-flex',
              alignItems: 'center',
              gap: 8,
              padding: '14px 32px',
              borderRadius: 9999,
              background: 'transparent',
              color: '#fff',
              fontWeight: 600,
              fontSize: 15,
              textDecoration: 'none',
              border: '1px solid rgba(255,255,255,0.3)',
              transition: 'transform 0.2s, background 0.2s',
            }}>
              {lang === 'en' ? 'Register as Artist →' : 'アーティストとして登録 →'}
            </a>
          </div>
        </div>
      </section>

      {/* ========== SECTION 3: FOUNDER STRIP ========== */}
      <section id="founder" className="founder-strip" style={{
        padding: '64px 20px',
        background: '#fff',
        borderBottom: '1px solid #e5e2dc',
      }}>
        <div style={{
          maxWidth: 800,
          margin: '0 auto',
          textAlign: 'center',
        }}>
          <div style={{
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            gap: 16,
            marginBottom: 32,
          }}>
            <div className="founder-photo" style={{
              width: 96,
              height: 96,
              borderRadius: '50%',
              background: 'linear-gradient(135deg, #c4956a 0%, #e85d3a 100%)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              fontSize: 36,
              color: '#fff',
              fontWeight: 700,
              boxShadow: '0 4px 20px rgba(196,149,106,0.25)',
              overflow: 'hidden',
            }}>
              {/* Replace with <img src="/images/founder.jpg" ... /> when available */}
              S
            </div>

            <div>
              <p style={{
                fontSize: 18,
                fontWeight: 700,
                color: '#1a1a1a',
                margin: '0 0 4px',
                fontStyle: 'italic',
              }}>
                {lang === 'en'
                  ? 'Built by a musician, for musicians.'
                  : '音楽家が、音楽家のために作りました。'}
              </p>
              <p style={{
                fontSize: 14,
                color: '#6b6560',
                margin: 0,
                lineHeight: 1.6,
              }}>
                {lang === 'en'
                  ? "Satoshi Yamashita — Drummer (ROUTE14band), Secretary General of Japan's Independent Labels Council"
                  : '山下 智 — ドラマー（ROUTE14band）、一般社団法人インディペンデント・レーベル協議会 事務局長'}
              </p>
            </div>
          </div>

          {/* 3 Badge Cards */}
          <div className="founder-badges" style={{
            display: 'flex',
            justifyContent: 'center',
            gap: 20,
            flexWrap: 'wrap',
            marginBottom: 32,
          }}>
            {[
              {
                icon: <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="#c4956a" strokeWidth="2" strokeLinecap="round"><line x1="4" y1="20" x2="16" y2="8"/><line x1="8" y1="20" x2="20" y2="8"/><circle cx="17.5" cy="6.5" r="2.5" fill="#c4956a" stroke="none"/><circle cx="13.5" cy="6.5" r="2.5" fill="#c4956a" stroke="none"/></svg>,
                num: lang === 'en' ? '10 years' : '10回出演',
                label: lang === 'en' ? 'at SXSW' : 'SXSW出演',
              },
              {
                icon: <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="#c4956a" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><path d="M3 21h18M5 21V7l7-4 7 4v14M9 21v-4h6v4"/><line x1="9" y1="10" x2="9" y2="10.01"/><line x1="15" y1="10" x2="15" y2="10.01"/><line x1="9" y1="14" x2="9" y2="14.01"/><line x1="15" y1="14" x2="15" y2="14.01"/></svg>,
                num: '70+',
                label: lang === 'en' ? 'Industry network' : '業界ネットワーク',
              },
              {
                icon: <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="#c4956a" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><path d="M8 21h8M12 17v4M7 4h10M7 4c0 0-2 0-2 3s2 5 2 5M17 4c0 0 2 0 2 3s-2 5-2 5M7 12c1 2 3 3 5 3s4-1 5-3"/></svg>,
                num: 'Grammy',
                label: lang === 'en' ? 'Award entrant' : '賞エントリー',
              },
            ].map((badge, i) => (
              <div key={i} style={{
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'center',
                gap: 6,
                padding: '16px 24px',
                background: '#f8f7f4',
                borderRadius: 12,
                minWidth: 130,
                border: '1px solid #e5e2dc',
              }}>
                <div style={{ height: 22, display: 'flex', alignItems: 'center' }}>{badge.icon}</div>
                <span style={{
                  fontSize: 22,
                  fontWeight: 700,
                  color: '#c4956a',
                  lineHeight: 1,
                }}>{badge.num}</span>
                <span style={{
                  fontSize: 12,
                  color: '#6b6560',
                  textTransform: 'uppercase',
                  letterSpacing: '0.5px',
                }}>{badge.label}</span>
              </div>
            ))}
          </div>

          {/* Quote */}
          <blockquote style={{
            fontSize: 16,
            color: '#1a1a1a',
            fontStyle: 'italic',
            margin: '0 0 12px',
            lineHeight: 1.7,
            position: 'relative',
            paddingLeft: 0,
          }}>
            <span style={{ color: '#c4956a', fontSize: 24, verticalAlign: 'text-top', lineHeight: 1 }}>&ldquo;</span>
            {lang === 'en'
              ? "Music connects people — even when words can't."
              : '言葉が通じなくても、音楽で人は喜ぶ。'}
            <span style={{ color: '#c4956a', fontSize: 24, verticalAlign: 'text-top', lineHeight: 1 }}>&rdquo;</span>
          </blockquote>

          <a
            href="https://ilcj.com/news/192/"
            target="_blank"
            rel="noopener noreferrer"
            style={{
              fontSize: 13,
              color: '#c4956a',
              textDecoration: 'none',
              fontWeight: 500,
            }}
          >
            {lang === 'en' ? 'Read the full story →' : 'インタビュー記事を読む →'}
          </a>
        </div>
      </section>

      {/* ========== SECTION 4: HOW IT WORKS ========== */}
      <section id="how-it-works" style={{ background: '#faf8f5', padding: '100px 0' }} className="section-pad">
        <div style={wrap}>
          <AnimatedSection>
            <div style={{ textAlign: 'center', marginBottom: 56 }}>
              <div style={{ width: 40, height: 3, borderRadius: 2, background: 'linear-gradient(90deg, #c4956a, #e85d3a)', margin: '0 auto 16px' }} />
              <div style={{ fontSize: 13, fontWeight: 600, letterSpacing: '3px', color: '#c4956a', textTransform: 'uppercase', marginBottom: 20 }}>{t.how.label}</div>
              <h2 style={{ fontFamily: D.fHead, fontSize: 'clamp(28px, 5vw, 44px)', fontWeight: 700, color: L.text, lineHeight: 1.25 }}>{t.how.title}</h2>
            </div>
          </AnimatedSection>

          <div className="how-grid artist-steps-grid" style={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: 16 }}>
            {t.how.steps.map((step, i) => (
              <AnimatedSection key={i} delay={i * 100}>
                <div className="how-card-light artist-step-card step-card" style={{ padding: 24 }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 12 }}>
                    {/* Step number circle — replaces emoji icons */}
                    <div style={{
                      width: 40,
                      height: 40,
                      borderRadius: '50%',
                      background: 'rgba(196,149,106,0.1)',
                      border: '1px solid rgba(196,149,106,0.3)',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      fontSize: 16,
                      fontWeight: 700,
                      color: '#c4956a',
                      flexShrink: 0,
                    }}>
                      {String(i + 1).padStart(2, '0')}
                    </div>
                  </div>
                  <h3 className="step-title" style={{ fontSize: 16, fontWeight: 600, color: L.text, marginBottom: 8 }}>{step.t}</h3>
                  <p className="step-desc" style={{ fontSize: 14, color: L.textSec, lineHeight: 1.5, margin: 0 }}>{step.d}</p>
                </div>
              </AnimatedSection>
            ))}
          </div>

          <AnimatedSection delay={300}>
            <div style={{ textAlign: 'center', marginTop: 48 }}>
              <a href="/artist" className="cta-coral cta-button" style={{ fontSize: 16, padding: '15px 36px' }}>{t.how.cta}</a>
            </div>
          </AnimatedSection>
        </div>
      </section>

      {/* ========== SECTION 5: FOR CURATORS ========== */}
      <AnimatedSection>
        <section id="for-curators" className="for-curators-section" style={{
          padding: '80px 20px',
          background: '#1a1715',
          color: '#fff',
        }}>
          <div style={{ maxWidth: 900, margin: '0 auto' }}>
            <div style={{ textAlign: 'center', marginBottom: 48 }}>
              <h2 style={{
                fontSize: 32,
                fontWeight: 700,
                marginBottom: 12,
                color: '#f0ede6',
                fontFamily: D.fHead,
              }}>
                {lang === 'en' ? 'For Curators & Media' : 'キュレーター・メディアの方へ'}
              </h2>
              <p style={{
                fontSize: 17,
                color: 'rgba(240,237,230,0.7)',
                maxWidth: 500,
                margin: '0 auto',
              }}>
                {lang === 'en'
                  ? "Discover Japan's best independent music — and get paid for every review."
                  : '日本の優れたインディー音楽を発見し、レビューごとに報酬を受け取れます。'}
              </p>
              <p style={{
                fontSize: 13,
                color: 'rgba(240,237,230,0.5)',
                textAlign: 'center',
                marginTop: -8,
                marginBottom: 32,
              }}>
                {lang === 'en'
                  ? '— Playlist curators, music bloggers, radio DJs, and media outlets'
                  : '— プレイリスト運営者・音楽ブロガー・ラジオDJ・音楽メディアの方'}
              </p>
            </div>

            {/* Live photo — shows what kind of artists curators will discover */}
            <div className="live-photo" style={{
              marginBottom: 40,
              borderRadius: 16,
              overflow: 'hidden',
              maxWidth: 700,
              margin: '0 auto 40px',
              position: 'relative',
            }}>
              <img
                src="/images/sxsw-trumpet.jpg"
                alt={lang === 'en'
                  ? 'Japanese indie artists performing at SXSW'
                  : 'SXSWで演奏する日本のインディーアーティスト'}
                style={{
                  width: '100%',
                  display: 'block',
                  borderRadius: 16,
                }}
              />
              <div style={{
                position: 'absolute',
                bottom: 0,
                left: 0,
                right: 0,
                padding: '24px 20px 16px',
                background: 'linear-gradient(transparent, rgba(0,0,0,0.7))',
                borderRadius: '0 0 16px 16px',
              }}>
                <p style={{
                  fontSize: 12,
                  color: 'rgba(255,255,255,0.7)',
                  margin: 0,
                  textAlign: 'center',
                }}>
                  {lang === 'en'
                    ? 'ROUTE14band performing at SXSW, Austin TX'
                    : 'ROUTE14band — SXSW（テキサス州オースティン）でのライブ'}
                </p>
              </div>
            </div>

            {/* 3 Benefit Cards */}
            <div style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
              gap: 20,
              marginBottom: 40,
            }}>
              {[
                {
                  icon: <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="#c4956a" strokeWidth="1.5" strokeLinecap="round"><circle cx="12" cy="12" r="9"/><path d="M14.5 9.5c-.5-1-1.5-1.5-2.5-1.5s-2 .5-2 1.5 1.5 1.5 2.5 2 2.5 1 2.5 2-1 1.5-2 1.5-2-.5-2.5-1.5M12 6.5v1M12 16.5v1"/></svg>,
                  title: lang === 'en' ? '$1+ per review' : '$1+/レビュー',
                  desc: lang === 'en'
                    ? 'Guaranteed compensation for every response — accept, decline, or feedback.'
                    : 'すべての回答に報酬が保証。採用・不採用・フィードバックいずれでも。',
                },
                {
                  icon: <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="#c4956a" strokeWidth="1.5" strokeLinecap="round"><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1" fill="#c4956a"/></svg>,
                  title: lang === 'en' ? 'AI-matched to your taste' : 'AIがあなたの好みにマッチ',
                  desc: lang === 'en'
                    ? 'Only receive pitches that match your genres, mood preferences, and audio profile.'
                    : 'ジャンル・ムード・音響プロフィールに合うピッチのみ受信。',
                },
                {
                  icon: <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="#c4956a" strokeWidth="1.5" strokeLinecap="round"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 3"/></svg>,
                  title: lang === 'en' ? '7-day response window' : '7日間の回答猶予',
                  desc: lang === 'en'
                    ? 'Review at your own pace. No pressure, no deadlines stacking up.'
                    : 'あなたのペースでレビュー。プレッシャーなし。',
                },
              ].map((card, i) => (
                <div key={i} className="benefit-card" style={{
                  padding: '28px 24px',
                  background: 'rgba(255,255,255,0.05)',
                  borderRadius: 16,
                  border: '1px solid rgba(255,255,255,0.08)',
                }}>
                  <div style={{ marginBottom: 12 }}>{card.icon}</div>
                  <h3 style={{
                    fontSize: 18,
                    fontWeight: 700,
                    color: '#f0ede6',
                    marginBottom: 8,
                  }}>{card.title}</h3>
                  <p style={{
                    fontSize: 14,
                    color: 'rgba(240,237,230,0.6)',
                    lineHeight: 1.6,
                    margin: 0,
                  }}>{card.desc}</p>
                </div>
              ))}
            </div>

            {/* Curator value proposition — concrete numbers */}
            <div style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
              gap: 16,
              marginBottom: 40,
            }}>
              {[
                {
                  num: '70+',
                  title: lang === 'en' ? 'Label network' : 'レーベルネットワーク',
                  desc: lang === 'en'
                    ? "Our founder's deep connections with Japan's independent label scene bring you undiscovered talent."
                    : '創業者の日本インディーレーベル業界との深い繋がりから、まだ知られていない才能が届きます。',
                },
                {
                  num: lang === 'en' ? 'AI-filtered' : 'AI精査済み',
                  title: lang === 'en' ? 'Quality pitches only' : '高品質ピッチのみ',
                  desc: lang === 'en'
                    ? 'Audio analysis ensures you only receive music that matches your taste.'
                    : '音響分析により、あなたの好みに合う音楽だけが届きます。',
                },
                {
                  num: lang === 'en' ? '3 min' : '3分',
                  title: lang === 'en' ? 'Quick sign-up' : '登録はすぐ完了',
                  desc: lang === 'en'
                    ? 'Set your genres, moods, and preferences. Start receiving pitches.'
                    : 'ジャンル・ムード・好みを設定するだけ。すぐにピッチを受信開始。',
                },
              ].map((item, i) => (
                <div key={i} className="value-card" style={{
                  padding: '24px 20px',
                  background: 'rgba(255,255,255,0.05)',
                  borderRadius: 12,
                  border: '1px solid rgba(255,255,255,0.08)',
                  textAlign: 'center',
                }}>
                  <div style={{
                    fontSize: 28,
                    fontWeight: 700,
                    color: '#c4956a',
                    lineHeight: 1,
                    marginBottom: 8,
                    fontStyle: 'italic',
                  }}>{item.num}</div>
                  <div style={{
                    fontSize: 14,
                    fontWeight: 600,
                    color: '#f0ede6',
                    marginBottom: 6,
                  }}>{item.title}</div>
                  <div style={{
                    fontSize: 12,
                    color: 'rgba(240,237,230,0.6)',
                    lineHeight: 1.5,
                  }}>{item.desc}</div>
                </div>
              ))}
            </div>

            {/* Early Adopter Benefits Box */}
            <div className="early-adopter-box" style={{
              padding: '32px',
              background: 'linear-gradient(135deg, rgba(196,149,106,0.1) 0%, rgba(232,93,58,0.08) 100%)',
              borderRadius: 16,
              border: '1px solid rgba(196,149,106,0.2)',
              marginBottom: 32,
            }}>
              <div style={{
                display: 'flex',
                alignItems: 'center',
                gap: 10,
                marginBottom: 16,
              }}>
                <span style={{
                  width: 3,
                  height: 20,
                  borderRadius: 2,
                  background: 'linear-gradient(180deg, #c4956a, #e85d3a)',
                  flexShrink: 0,
                }} />
                <span style={{
                  fontSize: 16,
                  fontWeight: 700,
                  color: '#c4956a',
                }}>
                  {lang === 'en'
                    ? 'Register now, be ready at launch'
                    : '今登録すれば、ローンチ初日からスタート'}
                </span>
              </div>
              <div style={{
                display: 'flex',
                flexDirection: 'column',
                gap: 10,
              }}>
                {(lang === 'en' ? [
                  'First to receive AI-matched pitches from Japanese artists',
                  'Set up your profile and preferences before the rush',
                  'Priority placement in artist search results',
                ] : [
                  'AIマッチングされたピッチを最初に受け取れる',
                  '楽曲が集まる前にプロフィールを整備できる',
                  'アーティストの検索結果で優先表示',
                ]).map((item, i) => (
                  <div key={i} style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: 10,
                  }}>
                    <svg width="14" height="14" viewBox="0 0 16 16" fill="none"><path d="M3 8l3.5 3.5L13 5" stroke="#4ade80" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg>
                    <span style={{
                      fontSize: 14,
                      color: 'rgba(240,237,230,0.8)',
                    }}>{item}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* CTA */}
            <div style={{ textAlign: 'center' }}>
              <a href="/curator" className="cta-button" style={{
                display: 'inline-flex',
                alignItems: 'center',
                gap: 8,
                padding: '14px 36px',
                borderRadius: 9999,
                background: '#c4956a',
                color: '#fff',
                fontWeight: 600,
                fontSize: 15,
                textDecoration: 'none',
                boxShadow: '0 4px 20px rgba(196,149,106,0.3)',
              }}>
                {lang === 'en' ? 'Register as Curator →' : 'キュレーター（音楽メディア）として登録 →'}
              </a>
            </div>
          </div>
        </section>
      </AnimatedSection>

      {/* ========== SECTION 6: FOR ARTISTS ========== */}
      <AnimatedSection>
        <section id="for-artists" className="for-artists-section" style={{
          padding: '80px 20px',
          background: '#f8f7f4',
        }}>
          <div style={{ maxWidth: 900, margin: '0 auto' }}>
            <div style={{ textAlign: 'center', marginBottom: 48 }}>
              <h2 style={{
                fontSize: 32,
                fontWeight: 700,
                color: '#1a1a1a',
                marginBottom: 12,
                fontFamily: D.fHead,
              }}>
                {lang === 'en' ? 'Beyond distribution.' : '配信したその先へ。'}
              </h2>
              <p style={{
                fontSize: 17,
                color: '#6b6560',
                maxWidth: 500,
                margin: '0 auto',
              }}>
                {lang === 'en'
                  ? "There's a way to get your music heard by the right people."
                  : '音楽を「聴いてほしい人」に届ける方法があります。'}
              </p>
            </div>

            {/* Common mistakes — what doesn't work */}
            <div style={{
              maxWidth: 700,
              margin: '0 auto 48px',
              padding: '32px 28px',
              background: '#fff',
              borderRadius: 16,
              border: '1px solid #e5e2dc',
            }}>
              <p style={{
                fontSize: 15,
                fontWeight: 600,
                color: '#1a1a1a',
                marginBottom: 20,
                textAlign: 'center',
              }}>
                {lang === 'en'
                  ? "Common ways artists try to grow — and why they don't work"
                  : 'こんな方法で再生数を増やそうとしていませんか？'}
              </p>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
                {[
                  {
                    en: 'Paying bots to inflate stream counts',
                    ja: 'ボット業者に頼んで再生数を水増し',
                    enD: 'Risk of account suspension. Zero real fans gained.',
                    jaD: 'アカウント停止のリスク。本当のファンは1人も増えません。',
                  },
                  {
                    en: 'Paying influencers to use your track as BGM',
                    ja: 'インフルエンサーにBGMとして使ってもらう',
                    enD: 'Indirect exposure — viewers come for the influencer, not your music.',
                    jaD: '間接的な露出。視聴者はインフルエンサー目当てで、あなたの音楽を聴きに来ません。',
                  },
                  {
                    en: 'Grinding on social media every day',
                    ja: 'SNSでひたすら宣伝し続ける',
                    enD: 'Only reaches existing followers. Exhausting and unsustainable.',
                    jaD: 'フォロワー以外には届かない。疲弊するだけで持続できません。',
                  },
                ].map((item, i) => (
                  <div key={i} style={{ display: 'flex', gap: 12, alignItems: 'flex-start' }}>
                    <span style={{ fontSize: 16, color: '#e85d3a', fontWeight: 700, flexShrink: 0, lineHeight: '24px' }}>×</span>
                    <div>
                      <p style={{ fontSize: 14, fontWeight: 600, color: '#1a1a1a', margin: '0 0 4px' }}>
                        {lang === 'en' ? item.en : item.ja}
                      </p>
                      <p style={{ fontSize: 13, color: '#6b6560', margin: 0, lineHeight: 1.5 }}>
                        {lang === 'en' ? item.enD : item.jaD}
                      </p>
                    </div>
                  </div>
                ))}
                <div style={{ width: '100%', height: 1, background: '#e5e2dc', margin: '4px 0' }} />
                <div style={{ display: 'flex', gap: 12, alignItems: 'flex-start' }}>
                  <span style={{ fontSize: 16, color: '#4ade80', fontWeight: 700, flexShrink: 0, lineHeight: '24px' }}>✓</span>
                  <div>
                    <p style={{ fontSize: 14, fontWeight: 600, color: '#1a1a1a', margin: '0 0 4px' }}>
                      {lang === 'en'
                        ? 'OTONAMI: Reach real music fans through professional curators'
                        : 'OTONAMIなら：プロのキュレーターを通じて、本当の音楽ファンに届く'}
                    </p>
                    <p style={{ fontSize: 13, color: '#6b6560', margin: 0, lineHeight: 1.5 }}>
                      {lang === 'en'
                        ? 'Playlist curators, music bloggers, and radio DJs listen to your track, give honest feedback, and share it with their audience — real people who love discovering new music.'
                        : '海外のプレイリスト運営者・音楽ブロガー・ラジオDJがあなたの曲を実際に聴き、正直なフィードバックをくれて、彼らのオーディエンスに届けてくれます。新しい音楽を探している本物の音楽ファンに届きます。'}
                    </p>
                  </div>
                </div>
              </div>
            </div>

            {/* 3 Barriers Cards */}
            <div style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
              gap: 20,
              marginBottom: 40,
            }}>
              {[
                {
                  icon: <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="#c4956a" strokeWidth="1.5" strokeLinecap="round"><circle cx="12" cy="12" r="9"/><path d="M3.6 9h16.8M3.6 15h16.8"/><ellipse cx="12" cy="12" rx="4" ry="9"/></svg>,
                  title: lang === 'en' ? 'Language barrier' : '言語の壁',
                  desc: lang === 'en'
                    ? "Don't speak English? No problem. AI creates professional English introductions from your Japanese input."
                    : '英語が苦手でも大丈夫。AIがあなたの日本語から、プロの英語紹介文を自動作成します。',
                },
                {
                  icon: <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="#c4956a" strokeWidth="1.5" strokeLinecap="round"><path d="M9 8h6M9 12h6M9 16h4"/><rect x="4" y="4" width="16" height="16" rx="2"/></svg>,
                  title: lang === 'en' ? 'Cost barrier' : 'コストの壁',
                  desc: lang === 'en'
                    ? 'Reach international music media from ¥160 per submission. Overseas PR agencies charge ¥300K-1M/month.'
                    : '1件¥160〜で海外の音楽メディアに直接届けられます。PR会社に頼むと月30〜100万円。',
                },
                {
                  icon: <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="#c4956a" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><path d="M15 3h4a2 2 0 012 2v14a2 2 0 01-2 2h-4M10 17l5-5-5-5M13.8 12H3"/></svg>,
                  title: lang === 'en' ? 'Access barrier' : 'アクセスの壁',
                  desc: lang === 'en'
                    ? "No need to hunt for contacts. AI finds the right playlist curators and music bloggers for your sound."
                    : '海外のプレイリスト運営者や音楽ブロガーの連絡先を自分で探す必要はありません。AIが最適な相手を見つけます。',
                },
              ].map((card, i) => (
                <div key={i} className="barrier-card" style={{
                  padding: '28px 24px',
                  background: '#fff',
                  borderRadius: 16,
                  border: '1px solid #e5e2dc',
                  borderTop: '3px solid #c4956a',
                }}>
                  <div style={{ marginBottom: 12 }}>{card.icon}</div>
                  <h3 style={{
                    fontSize: 18,
                    fontWeight: 700,
                    color: '#1a1a1a',
                    marginBottom: 8,
                  }}>{card.title}</h3>
                  <p style={{
                    fontSize: 14,
                    color: '#6b6560',
                    lineHeight: 1.6,
                    margin: 0,
                  }}>{card.desc}</p>
                </div>
              ))}
            </div>

            {/* Bridge text after 3 barriers */}
            <div style={{
              textAlign: 'center',
              margin: '8px 0 40px',
            }}>
              <div style={{
                width: 40,
                height: 3,
                background: 'linear-gradient(90deg, #c4956a, #e85d3a)',
                borderRadius: 2,
                margin: '0 auto 16px',
              }} />
              <p style={{
                fontSize: 15,
                fontWeight: 600,
                color: '#1a1a1a',
              }}>
                {lang === 'en'
                  ? 'OTONAMI solves all three — so you can focus on making music.'
                  : 'OTONAMIは、この3つの壁をすべて解決します。'}
              </p>
            </div>

            {/* Success Metrics — proven model */}
            <div style={{ textAlign: 'center', marginBottom: 16 }}>
              <p style={{
                fontSize: 13,
                fontWeight: 600,
                color: '#c4956a',
                letterSpacing: '1px',
                textTransform: 'uppercase',
                marginBottom: 8,
              }}>
                {lang === 'en' ? 'Proven Model' : '実証済みのモデル'}
              </p>
              <p style={{
                fontSize: 15,
                color: '#6b6560',
                maxWidth: 600,
                margin: '0 auto 24px',
                lineHeight: 1.6,
              }}>
                {lang === 'en'
                  ? 'Over 300,000 artists use similar platforms overseas. OTONAMI brings this model to Japan — with AI matching, Japanese UI, and AI-generated English pitches.'
                  : '海外では同様のプラットフォームで30万人以上のアーティストが活動中。OTONAMIはこの実証済みモデルに「日本語UI」「AIピッチ生成」「AIマッチング」を加えた日本初のサービスです。'}
              </p>
            </div>

            <div style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
              gap: 16,
              marginBottom: 48,
            }}>
              {[
                {
                  num: '2X',
                  title: lang === 'en' ? 'Spotify listeners' : 'Spotify月間リスナー増加',
                  desc: lang === 'en'
                    ? 'Artists who use curator pitching see double their monthly listeners on average.'
                    : 'キュレーターピッチ活用で月間リスナーが倍増した事例。',
                },
                {
                  num: '43K',
                  title: lang === 'en' ? 'Plays in 1 month' : '1ヶ月での再生回数',
                  desc: lang === 'en'
                    ? 'A single playlist placement can generate tens of thousands of streams.'
                    : '1つのプレイリスト掲載から短期間で獲得。',
                },
                {
                  num: '40%',
                  title: lang === 'en' ? 'Pitch acceptance rate' : 'ピッチ採用率',
                  desc: lang === 'en'
                    ? 'AI matching dramatically improves acceptance rates vs. cold emails.'
                    : '従来のメール営業では考えられない採用率を記録。',
                },
                {
                  num: '1/100',
                  title: lang === 'en' ? 'Cost reduction' : 'コスト削減',
                  desc: lang === 'en'
                    ? 'Compared to hiring an overseas PR agency, costs are reduced by 99%.'
                    : '海外PR会社と比較して1/100以下のコスト。',
                },
              ].map((item, i) => (
                <div key={i} className="metric-card" style={{
                  padding: '24px 20px',
                  background: '#fff',
                  borderRadius: 12,
                  border: '1px solid #e5e2dc',
                  textAlign: 'center',
                }}>
                  <div style={{
                    fontSize: 36,
                    fontWeight: 700,
                    color: '#c4956a',
                    lineHeight: 1,
                    marginBottom: 8,
                    fontStyle: 'italic',
                  }}>{item.num}</div>
                  <div style={{
                    fontSize: 14,
                    fontWeight: 600,
                    color: '#1a1a1a',
                    marginBottom: 6,
                  }}>{item.title}</div>
                  <div style={{
                    fontSize: 12,
                    color: '#6b6560',
                    lineHeight: 1.5,
                  }}>{item.desc}</div>
                </div>
              ))}
            </div>

            {/* Comparison Table */}
            <div style={{ marginBottom: 48 }}>
              <p style={{
                fontSize: 13,
                fontWeight: 600,
                color: '#c4956a',
                letterSpacing: '1px',
                textTransform: 'uppercase',
                textAlign: 'center',
                marginBottom: 8,
              }}>
                {lang === 'en' ? 'Why OTONAMI' : 'OTONAMIの優位性'}
              </p>
              <h3 style={{
                fontSize: 22,
                fontWeight: 700,
                color: '#1a1a1a',
                textAlign: 'center',
                marginBottom: 24,
              }}>
                {lang === 'en' ? 'Compared to alternatives' : '従来の方法との比較'}
              </h3>

              <div className="comparison-table" style={{
                overflowX: 'auto',
                borderRadius: 12,
                border: '1px solid #e5e2dc',
              }}>
                <table style={{
                  width: '100%',
                  borderCollapse: 'collapse',
                  fontSize: 14,
                  minWidth: 600,
                }}>
                  <thead>
                    <tr>
                      <th style={{
                        padding: '14px 16px',
                        textAlign: 'left',
                        background: '#f8f7f4',
                        borderBottom: '1px solid #e5e2dc',
                        color: '#6b6560',
                        fontWeight: 500,
                      }}></th>
                      <th style={{
                        padding: '14px 16px',
                        textAlign: 'left',
                        background: '#c4956a',
                        color: '#fff',
                        fontWeight: 700,
                        borderBottom: '1px solid #e5e2dc',
                      }}>OTONAMI</th>
                      <th style={{
                        padding: '14px 16px',
                        textAlign: 'left',
                        background: '#f8f7f4',
                        borderBottom: '1px solid #e5e2dc',
                        color: '#6b6560',
                        fontWeight: 500,
                      }}>{lang === 'en' ? 'Overseas services' : '海外の類似サービス'}</th>
                      <th style={{
                        padding: '14px 16px',
                        textAlign: 'left',
                        background: '#f8f7f4',
                        borderBottom: '1px solid #e5e2dc',
                        color: '#6b6560',
                        fontWeight: 500,
                      }}>{lang === 'en' ? 'Cold email' : '自力でのメール営業'}</th>
                    </tr>
                  </thead>
                  <tbody>
                    {[
                      {
                        label: lang === 'en' ? 'Language' : '操作言語',
                        otonami: lang === 'en' ? 'Japanese' : '日本語',
                        overseas: lang === 'en' ? 'English only' : '英語のみ',
                        diy: lang === 'en' ? 'English required' : '英語必須',
                      },
                      {
                        label: lang === 'en' ? 'Pitch writing' : 'ピッチ文作成',
                        otonami: lang === 'en' ? 'AI auto-generated (EN)' : 'AI自動生成（英語）',
                        overseas: lang === 'en' ? 'Manual in English' : '手動で英語入力',
                        diy: lang === 'en' ? 'Write your own' : '自分で英語作成',
                      },
                      {
                        label: lang === 'en' ? 'Curator matching' : 'キュレーター選定',
                        otonami: lang === 'en' ? 'AI Match Score (auto)' : 'AIマッチスコア（自動）',
                        overseas: lang === 'en' ? 'Manual filter' : '手動フィルター',
                        diy: lang === 'en' ? 'Research yourself' : '自分でリサーチ',
                      },
                      {
                        label: lang === 'en' ? 'Audio analysis' : '楽曲分析',
                        otonami: lang === 'en' ? 'AI auto (BPM, genre, mood)' : 'AI自動（BPM・ジャンル・ムード）',
                        overseas: lang === 'en' ? 'None' : 'なし',
                        diy: lang === 'en' ? 'None' : 'なし',
                      },
                      {
                        label: lang === 'en' ? 'Feedback' : 'フィードバック',
                        otonami: lang === 'en' ? 'Guaranteed within 7 days' : '7日以内に保証',
                        overseas: lang === 'en' ? '7-48 hours' : '7日〜48時間',
                        diy: lang === 'en' ? '<3% reply rate' : '返信率3%以下',
                      },
                      {
                        label: lang === 'en' ? 'Price' : '価格',
                        otonami: lang === 'en' ? '~¥160 per pitch' : '約¥160/件〜',
                        overseas: lang === 'en' ? '~¥150-450 per pitch' : '約¥150〜450/件',
                        diy: lang === 'en' ? 'Free (huge time cost)' : '無料（時間コスト大）',
                      },
                      {
                        label: lang === 'en' ? 'Japanese music expertise' : '日本音楽への理解',
                        otonami: lang === 'en' ? 'Japan-specialized curators' : '日本音楽に特化したキュレーター',
                        overseas: lang === 'en' ? 'Global (generic)' : '汎用（全世界対象）',
                        diy: lang === 'en' ? 'Depends on recipient' : '相手次第',
                      },
                    ].map((row, i) => (
                      <tr key={i}>
                        <td style={{
                          padding: '12px 16px',
                          borderBottom: '1px solid #e5e2dc',
                          fontWeight: 500,
                          color: '#1a1a1a',
                        }}>{row.label}</td>
                        <td style={{
                          padding: '12px 16px',
                          borderBottom: '1px solid #e5e2dc',
                          color: '#1a1a1a',
                          fontWeight: 500,
                          background: 'rgba(196,149,106,0.05)',
                        }}>{row.otonami}</td>
                        <td style={{
                          padding: '12px 16px',
                          borderBottom: '1px solid #e5e2dc',
                          color: '#6b6560',
                        }}>{row.overseas}</td>
                        <td style={{
                          padding: '12px 16px',
                          borderBottom: '1px solid #e5e2dc',
                          color: '#6b6560',
                        }}>{row.diy}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              <p style={{
                textAlign: 'center',
                fontSize: 13,
                color: '#c4956a',
                marginTop: 16,
                fontWeight: 500,
              }}>
                {lang === 'en'
                  ? 'OTONAMI advantage: Japanese UI + AI English pitch generation + AI Match Score'
                  : 'OTONAMIだけの強み：日本語UI + AI英語ピッチ自動生成 + AIマッチスコア'}
              </p>
            </div>

            {/* Artist live photo — emotional connection */}
            <div className="live-photo" style={{
              marginBottom: 32,
              borderRadius: 16,
              overflow: 'hidden',
              position: 'relative',
            }}>
              <img
                src="/images/stage-performance.jpg"
                alt={lang === 'en'
                  ? 'Japanese indie band performing on international stage'
                  : '海外ステージで演奏する日本のインディーバンド'}
                style={{
                  width: '100%',
                  display: 'block',
                  borderRadius: 16,
                }}
              />
              <div style={{
                position: 'absolute',
                bottom: 0,
                left: 0,
                right: 0,
                padding: '24px 20px 16px',
                background: 'linear-gradient(transparent, rgba(0,0,0,0.7))',
                borderRadius: '0 0 16px 16px',
              }}>
                <p style={{
                  fontSize: 13,
                  color: '#fff',
                  margin: 0,
                  textAlign: 'center',
                  fontWeight: 500,
                }}>
                  {lang === 'en'
                    ? 'Your music could be on stages like these.'
                    : 'あなたの音楽も、こんなステージに届けられる。'}
                </p>
              </div>
            </div>

            {/* Dashboard Screenshot */}
            <div style={{
              marginBottom: 40,
              borderRadius: 16,
              overflow: 'hidden',
              border: '1px solid #e5e2dc',
              boxShadow: '0 4px 24px rgba(0,0,0,0.06)',
            }}>
              <img
                src="/images/bento/dashboard.png"
                alt="OTONAMI Artist Dashboard"
                style={{ width: '100%', display: 'block' }}
              />
            </div>

            {/* Early Adopter Benefits Box (Artist) */}
            <div className="early-adopter-box" style={{
              padding: '32px',
              background: '#fff',
              borderRadius: 16,
              border: '1px solid #e5e2dc',
              boxShadow: '0 2px 12px rgba(0,0,0,0.04)',
              marginBottom: 32,
            }}>
              <div style={{
                display: 'flex',
                alignItems: 'center',
                gap: 10,
                marginBottom: 16,
              }}>
                <span style={{
                  width: 3,
                  height: 20,
                  borderRadius: 2,
                  background: 'linear-gradient(180deg, #c4956a, #e85d3a)',
                  flexShrink: 0,
                }} />
                <span style={{
                  fontSize: 16,
                  fontWeight: 700,
                  color: '#c4956a',
                }}>
                  {lang === 'en'
                    ? 'Get set up now — pitch on day one'
                    : '今すぐ準備、ローンチ日にすぐピッチ'}
                </span>
              </div>
              <div style={{
                display: 'flex',
                flexDirection: 'column',
                gap: 10,
              }}>
                {(lang === 'en' ? [
                  'Add your tracks and build your artist profile',
                  'AI will pre-generate pitch drafts before launch',
                  'Be first to reach curators when we go live',
                ] : [
                  '楽曲登録とプロフィール設定を先に完了できる',
                  'AIピッチ文がローンチ前に事前生成される',
                  'ローンチ初日にキュレーターへ即アプローチ',
                ]).map((item, i) => (
                  <div key={i} style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: 10,
                  }}>
                    <svg width="14" height="14" viewBox="0 0 16 16" fill="none"><path d="M3 8l3.5 3.5L13 5" stroke="#4ade80" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg>
                    <span style={{ fontSize: 14, color: '#1a1a1a' }}>{item}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* CTA */}
            <div style={{ textAlign: 'center' }}>
              <a href="/artist" className="cta-button" style={{
                display: 'inline-flex',
                alignItems: 'center',
                gap: 8,
                padding: '14px 36px',
                borderRadius: 9999,
                background: '#c4956a',
                color: '#fff',
                fontWeight: 600,
                fontSize: 15,
                textDecoration: 'none',
                boxShadow: '0 4px 20px rgba(196,149,106,0.3)',
              }}>
                {lang === 'en' ? 'Register as Artist (Free) →' : 'アーティスト登録（無料）→'}
              </a>
              <p style={{
                fontSize: 13,
                color: '#6b6560',
                marginTop: 12,
              }}>
                {lang === 'en'
                  ? 'Free to register. Credits purchased only when you pitch.'
                  : '登録無料。クレジットはピッチ送信時のみ購入。'}
              </p>
            </div>
          </div>
        </section>
      </AnimatedSection>

      {/* ========== SECTION 7: FAQ ========== */}
      <AnimatedSection>
        <section style={{
          padding: '80px 20px',
          background: '#fff',
        }}>
          <div style={{ maxWidth: 700, margin: '0 auto' }}>
            <h2 style={{
              fontSize: 28,
              fontWeight: 700,
              textAlign: 'center',
              marginBottom: 48,
              color: '#1a1a1a',
              fontFamily: D.fHead,
            }}>
              {lang === 'en' ? 'Frequently Asked Questions' : 'よくあるご質問'}
            </h2>

            {/* Curator FAQs */}
            <p style={{
              fontSize: 13,
              fontWeight: 600,
              color: '#c4956a',
              textTransform: 'uppercase',
              letterSpacing: '1px',
              marginBottom: 16,
            }}>
              {lang === 'en' ? 'For Curators' : 'キュレーター向け'}
            </p>
            {curatorFaqs.map((faq, i) => (
              <FAQItem
                key={`c-${i}`}
                question={faq.q}
                answer={faq.a}
                isOpen={openFaq === `c-${i}`}
                onClick={() => setOpenFaq(openFaq === `c-${i}` ? null : `c-${i}`)}
              />
            ))}

            <div style={{ height: 32 }} />

            {/* Artist FAQs */}
            <p style={{
              fontSize: 13,
              fontWeight: 600,
              color: '#c4956a',
              textTransform: 'uppercase',
              letterSpacing: '1px',
              marginBottom: 16,
            }}>
              {lang === 'en' ? 'For Artists' : 'アーティスト向け'}
            </p>
            {artistFaqs.map((faq, i) => (
              <FAQItem
                key={`a-${i}`}
                question={faq.q}
                answer={faq.a}
                isOpen={openFaq === `a-${i}`}
                onClick={() => setOpenFaq(openFaq === `a-${i}` ? null : `a-${i}`)}
              />
            ))}
          </div>
        </section>
      </AnimatedSection>

      {/* ========== SECTION 8: FOOTER ========== */}
      <footer style={{ background: '#151515', padding: '60px 0 40px', borderTop: `1px solid ${D.border}` }}>
        <div style={wrap}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 32, flexWrap: 'wrap', marginBottom: 48 }}>
            <div>
              <div style={{ fontFamily: D.fHead, fontSize: 22, letterSpacing: '2px', color: '#c4956a', marginBottom: 8 }}>OTONAMI</div>
              <div style={{ fontSize: 13, color: D.textMuted, lineHeight: 1.6 }}>
                {t.footer.tagline}
              </div>
            </div>
            <nav className="footer-links" style={{ display: 'flex', gap: 32, flexWrap: 'wrap', alignItems: 'center' }}>
              {t.footer.links.map((l, i) => (
                <a key={i} href={l.href} style={{ color: D.textMuted, textDecoration: 'none', fontSize: 13, transition: 'color 0.2s' }}
                  onMouseEnter={e => e.target.style.color = D.textSec}
                  onMouseLeave={e => e.target.style.color = D.textMuted}
                >{l.label}</a>
              ))}
            </nav>
          </div>
          <div style={{ borderTop: `1px solid ${D.border}`, paddingTop: 24, display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 12 }}>
            <span style={{ fontSize: 12, color: D.textMuted }}>{t.footer.copy}</span>
            <a href={`mailto:${t.footer.email}`} style={{ fontSize: 12, color: D.textMuted, textDecoration: 'none', transition: 'color 0.2s' }}
              onMouseEnter={e => e.target.style.color = D.textSec}
              onMouseLeave={e => e.target.style.color = D.textMuted}
            >{t.footer.email}</a>
          </div>
        </div>
      </footer>


      {/* ==========================================================================
          PRELAUNCH: HIDDEN SECTIONS — Restore after launch
          ========================================================================== */}

      {/* ========== PRELAUNCH: HIDDEN — Stats Bar (restore after launch) ==========
      <div className="stats-grid hero-stat-anim" style={{ display: 'grid', gridTemplateColumns: 'repeat(4,1fr)', gap: '0 32px', maxWidth: 640, margin: '0 auto' }}>
        {[
          { target: 3449, suffix: '',  l: lang === 'en' ? 'Curators & Pros' : '登録キュレーター' },
          { target: 70,   suffix: '+', l: lang === 'en' ? 'Partner Labels' : '対応レーベル' },
          { target: 10,   suffix: lang === 'en' ? '×' : '回', l: lang === 'en' ? 'Years at SXSW' : 'SXSW出演' },
          { target: 6,    suffix: '',  l: lang === 'en' ? 'Countries' : '対応国' },
        ].map((s, i) => (
          <div key={i} style={{ textAlign: 'center' }}>
            <div style={{ fontSize: 36, fontWeight: 600, color: '#c4956a', fontFamily: D.fHead, lineHeight: 1 }}>
              {s.target.toLocaleString()}{s.suffix}
            </div>
            <div style={{ fontSize: 11, color: D.textMuted, marginTop: 6, letterSpacing: '0.5px' }}>{s.l}</div>
          </div>
        ))}
      </div>
      ========== END HIDDEN ========== */}

      {/* ========== PRELAUNCH: HIDDEN — Why OTONAMI / Built for Curators (3 cards: AI-Matched / Get Paid / Japan's Hidden Gems) ==========
      <section style={{ background: '#1a1a1a', padding: '100px 0' }}>
        <div style={wrap}>
          <div style={{ textAlign: 'center', marginBottom: 56 }}>
            <div style={{ fontSize: 14, fontWeight: 600, letterSpacing: '3px', color: '#c4956a', textTransform: 'uppercase', marginBottom: 20 }}>
              {lang === 'en' ? 'FOR CURATORS & MEDIA' : 'キュレーターの方へ'}
            </div>
            <h2 style={{ fontFamily: D.fHead, fontSize: 'clamp(32px, 5vw, 48px)', fontWeight: 700, color: '#f0ede6', lineHeight: 1.3, maxWidth: 640, margin: '0 auto' }}>
              {lang === 'en' ? "Discover Japan's best independent music — curated for you." : '日本のベストなインディー音楽が、あなたのもとに届きます。'}
            </h2>
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: 24, marginBottom: 48 }}>
            {[
              { icon: '🎧', t: lang === 'en' ? 'Only music that matches your taste' : '厳選された楽曲だけが届く', d: lang === 'en' ? 'AI filters pitches by your genre, mood, and style preferences. No irrelevant submissions.' : 'あなたの好みに合わない楽曲は届きません。ジャンル・ムード・雰囲気でAIがフィルタリング。' },
              { icon: '💰', t: lang === 'en' ? 'Get paid to review' : 'レビューするだけで報酬', d: lang === 'en' ? 'Listen and provide feedback. Earn rewards for every review you complete.' : '楽曲を聴いてフィードバックを返すだけ。すべてのレビューに対して報酬をお支払いします。' },
              { icon: '🌏', t: lang === 'en' ? 'Discover music before anyone else' : 'まだ誰も知らない音楽に出会える', d: lang === 'en' ? "From SXSW veterans to underground singer-songwriters. Be the first to feature Japan's next breakout artist." : 'SXSW常連バンドから地方のシンガーソングライターまで。日本のインディーシーンの最前線をお届け。' },
            ].map((b, i) => (
              <div key={i} style={{ background: '#2a2a2a', border: '1px solid #3a3a3a', borderRadius: 12, padding: '32px 28px' }}>
                <div style={{ fontSize: 40, marginBottom: 16 }}>{b.icon}</div>
                <h3 style={{ fontSize: 17, fontWeight: 600, color: '#f0ede6', marginBottom: 12 }}>{b.t}</h3>
                <p style={{ fontSize: 14, color: '#b8b0a3', lineHeight: 1.7 }}>{b.d}</p>
              </div>
            ))}
          </div>
        </div>
      </section>
      ========== END HIDDEN ========== */}

      {/* ========== PRELAUNCH: HIDDEN — Success Stories (restore after launch) ==========
      <div style={{ marginTop: 72 }}>
        <div style={{ textAlign: 'center', marginBottom: 24 }}>
          <h3>{lang === 'en' ? 'Real results from curator pitching' : 'キュレーターピッチで実現した成果'}</h3>
        </div>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4,1fr)', gap: 16, marginBottom: 48 }}>
          {[
            { number: '2x', label: lang === 'en' ? 'Spotify listeners gained' : 'Spotify月間リスナー増加' },
            { number: '43K', label: lang === 'en' ? 'Plays in one month' : '1ヶ月での再生回数' },
            { number: '40%', label: lang === 'en' ? 'Pitch acceptance rate' : 'ピッチ採用率' },
            { number: '1/100', label: lang === 'en' ? 'Cost reduction' : 'コスト削減' },
          ].map((s, i) => (
            <div key={i} style={{ background: '#fff', border: '1px solid #e5e2dc', borderRadius: 16, padding: 24, textAlign: 'center' }}>
              <div style={{ fontSize: 44, fontWeight: 700, color: '#c4956a' }}>{s.number}</div>
              <div style={{ fontSize: 14, fontWeight: 700, color: '#1a1a1a' }}>{s.label}</div>
            </div>
          ))}
        </div>
      </div>
      ========== END HIDDEN ========== */}

      {/* ========== PRELAUNCH: HIDDEN — Comparison Table (restore after launch) ==========
      <div style={{ marginTop: 48 }}>
        <div style={{ textAlign: 'center', marginBottom: 24 }}>
          <h3>{lang === 'en' ? 'How we compare' : '従来の方法との比較'}</h3>
        </div>
        <table style={{ width: '100%', maxWidth: 900, margin: '0 auto', borderCollapse: 'collapse' }}>
          <thead>
            <tr>
              <th></th><th>OTONAMI</th><th>{lang === 'en' ? 'Other platforms' : '海外の類似サービス'}</th><th>{lang === 'en' ? 'DIY outreach' : '自力でのメール営業'}</th>
            </tr>
          </thead>
        </table>
      </div>
      ========== END HIDDEN ========== */}

      {/* ========== PRELAUNCH: HIDDEN — Promo Video Section (restore after launch) ==========
      <section style={{ background: 'linear-gradient(180deg, #1a1a1a 0%, #0a0a10 15%, #0a0a10 85%, #1a1a1a 100%)', padding: '80px 0' }}>
        <div style={{ textAlign: 'center', marginBottom: 40 }}>
          <h2>{lang === 'en' ? 'How OTONAMI works for you' : 'OTONAMIが届ける、新しい音楽体験'}</h2>
        </div>
        <OTONAMIPromo />
      </section>
      ========== END HIDDEN ========== */}

      {/* ========== PRELAUNCH: HIDDEN — Bento Grid Screenshot Showcase (restore after launch) ==========
      <section id="see-it-in-action" style={{ background: D.bg, padding: '80px 24px' }}>
        <div style={{ maxWidth: 1200, margin: '0 auto' }}>
          <div style={{ textAlign: 'center', marginBottom: 48 }}>
            <h2>{lang === 'en' ? 'Every screen, built for you' : 'すべての画面があなたのために'}</h2>
          </div>
          <div className="bento-grid">
            -- bento grid content --
          </div>
        </div>
      </section>
      ========== END HIDDEN ========== */}

      {/* ========== PRELAUNCH: HIDDEN — Trust / Social Proof (restore after launch) ==========
      <section style={{ background: D.bg, padding: '100px 0' }}>
        <div style={wrap}>
          <div style={{ textAlign: 'center', marginBottom: 48 }}>TRUSTED BY</div>
          <div style={{ display: 'flex', justifyContent: 'center', gap: 48 }}>
            <span>Japan Independent Music Scene</span>
            <span>SXSW — 10 Years</span>
          </div>
        </div>
      </section>
      ========== END HIDDEN ========== */}

      {/* ========== PRELAUNCH: HIDDEN — For Curators LIGHT section (restore after launch) ==========
      <section style={{ background: L.bg, padding: '100px 0' }}>
        <div style={wrap}>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 64 }}>
            <div>
              <h2>{lang === 'en' ? "Discover Japan's next breakout artist" : '日本の次のブレイクアーティストを発見'}</h2>
              <ul>
                <li>AI-matched recommendations based on your taste profile</li>
                <li>Listen before you commit</li>
                <li>Respond at your pace</li>
                <li>Compensation for your expertise ($1+ per review, paid via bank transfer)</li>
              </ul>
            </div>
          </div>
        </div>
      </section>
      ========== END HIDDEN ========== */}

      {/* ========== PRELAUNCH: HIDDEN — For Artists DARK section (restore after launch) ==========
      <section style={{ background: D.bg, padding: '100px 0' }}>
        <div style={wrap}>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 64 }}>
            <div>
              <h2>{lang === 'en' ? 'Your music deserves a global audience' : 'あなたの音楽は世界規模のオーディエンスに値する'}</h2>
            </div>
          </div>
        </div>
      </section>
      ========== END HIDDEN ========== */}

      {/* ========== PRELAUNCH: HIDDEN — CTA Banner (restore after launch) ==========
      <section style={{ background: 'linear-gradient(135deg, #c4956a 0%, #e85d3a 100%)', padding: '80px 0' }}>
        <div style={{ textAlign: 'center' }}>
          <h2>{lang === 'en' ? 'Ready to share your music with the world?' : 'あなたの音楽を、世界に届けませんか？'}</h2>
        </div>
      </section>
      ========== END HIDDEN ========== */}

      {/* ========== PRELAUNCH: HIDDEN — See It In Action / UI Mockup (restore after launch) ==========
      <section style={{ background: L.bg, padding: '0 0 100px' }}>
        <div style={wrap}>
          <div style={{ maxWidth: 820, margin: '0 auto', background: '#1a1a1a', borderRadius: 14, overflow: 'hidden' }}>
            -- mockup content --
          </div>
        </div>
      </section>
      ========== END HIDDEN ========== */}

    </div>
  );
}
